- name: Install and run nginx
  hosts: frontend
  become: yes   # sudo/root user
  tasks:
  - name: Install nginx server
    ansible.builtin.package:
      name: nginx
      state: present

  - name: Start nginx service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
      
      