- name: Install packages
  hosts: frontend
  become: yes
  tasks:
  - name: List of packages installed
    ansible.builtin.package:
      name: "{{ item }}"
      state: installed
    loop:
    - mysql
    - nginx
    - zip